feat: add observability controller
threeport/threeport pull request #180
Opened 2024-01-19 06:05 UTC by randalljohnson

2024-02-02 18:56 UTC, lander2k2 requested changes

2024-02-02 18:56 UTC, lander2k2 commented on pkg/api/v0/helm_workload.go
> +	ValuesDocument *string `json:"ValuesDocument,omitempty"  validate:"optional"`
```suggestion
	ValuesDocument *string `json:"ValuesDocument,omitempty" validate:"optional"`
```

2024-02-02 18:56 UTC, lander2k2 commented on cmd/tptctl/cmd/delete_observability_stack.go
> +	DeleteObservabilityStackCmd.Flags().StringVarP(
@randalljohnson This is my fault.  I gave you a bum steer when we did the review on this.  We decided a while back to *only* delete defined instance abstractions by config file.  Sorry I asked you to make this change 🤦 .  We need to revert it back to remove the name flag.

To summarize: We can delete by name or config file for any instance or definition.  But we only delete by config for defined instance abstractions.

2024-02-02 19:53 UTC, lander2k2 approved these changes

2024-02-08 17:48 UTC, HarisChoudhary approved these changes

2024-02-08 17:48 UTC, merged