feat: config based sdk
threeport/threeport pull request #258
Opened 2024-03-22 08:03 UTC by HarisChoudhary

2024-03-22 17:08 UTC, HarisChoudhary commented on .threeport/sdk-config.yaml
> +APIObjects:
APIObjectGroups

2024-03-22 17:22 UTC, HarisChoudhary commented on .threeport/sdk-config.yaml
> +      RouteExclude: true
Merge this and below to route-exclude

2024-03-22 17:27 UTC, HarisChoudhary commented on .threeport/sdk-config.yaml
> +      RouteExclude: true
ExcludeRoute

2024-03-22 17:33 UTC, HarisChoudhary commented on .threeport/sdk-config.yaml
> +      TptctlConfigPath: true
Merge with other tptctl to single struct:

type Tptctl struct {
	enabled  bool `yaml:",inline"`
	configPath bool
}

2024-03-22 17:34 UTC, HarisChoudhary commented on .threeport/sdk-config.yaml
> +      Versions:
Change databasemarker DatabaseExclude to ExcludeFromDb

2024-03-22 17:35 UTC, HarisChoudhary commented on .threeport/sdk-config.yaml
> +      LoadAssociationsFromDatabase: true
shorten database to db

2024-03-22 17:43 UTC, HarisChoudhary commented on .threeport/sdk-config.yaml
> +  aws:
# aws:
- Name: aws
  Objects:

2024-03-22 18:01 UTC, HarisChoudhary commented on cmd/sdk/cmd/gen/generate.go
> +	Long:  `Generate code for Threeport or its extensions.`,
Make this more descriptive. Synthesize summary for other three commands

2024-03-22 19:06 UTC, HarisChoudhary commented on cmd/sdk/cmd/create/api_objects.go
> +	Short: "Create threeport api objects.",
Create initial scaffloding for api objects

2024-03-22 19:07 UTC, HarisChoudhary commented on cmd/sdk/cmd/create/create.go
> +	Short: "Create aspects of the Threeport API or its extensions.",
Create initial source code scaffolding

2024-03-26 22:34 UTC, randalljohnson approved these changes
🚀

2024-03-27 13:11 UTC, lander2k2 commented
Suggested change on lines 40 and 47 of `internal/sdk/models/command.go':
```
...HeaderComment("originally generated by 'threeport-sdk codegen api-model' but will not be regenerated - intended for modification")
```
Should be:
```
...HeaderComment("originally generated by 'threeport-sdk codegen' for tptctl command scaffolding but will not be regenerated - intended for modification")
```

2024-03-27 14:37 UTC, lander2k2 requested changes

2024-03-27 14:37 UTC, lander2k2 commented on internal/sdk/sdk_config.go
> +type Tptctl struct {
```suggestion
// Tptctl contains attributes used by the SDK to generate tptctl
// command source code.
type Tptctl struct {
```

2024-03-27 19:30 UTC, lander2k2 commented
Suggest changing the `APIObjectManager` struct name to `CodegenManager` in `internal/sdk/api-object-manager/manager.go` to better align with its intended future purpose.

Would also make sense to change the directory from `api-object-manager` to `codegen-manager` and the package name from `apiobjectmanager` to `codegenmanager` as well.

2024-03-27 19:36 UTC, lander2k2 commented
Suggest changing the `SDKConfig` object and `APIObjectConfig` struct names.  And rearrange the ordering of the structs to represent the correct hierachy:

```
// was: type APIObjectConfig struct {
type SdkConfig struct {
	ApiObjectConfig `yaml:",inline"`
}

// APIObjectConfig contains the config for the threeport sdk to use
// It is a map of controller domains and the api objects under them
//was: type SDKConfig struct {
type ApiObjectConfig struct {
	ApiObjectGroups []*APIObjectGroup `yaml:"APIObjectGroups"`
}
```

2024-03-27 19:38 UTC, lander2k2 commented
For naming conventions in `internal/sdk/sdk_config.go` and `internal/sdk/api-object-manager/manager.go`, can we remove the all-caps for acronyms as per our [style guide](https://github.com/threeport/threeport/blob/main/docs/style-guide.md#naming)?

So `APIObject` becomes `ApiObject` etc.

2024-03-27 19:41 UTC, lander2k2 commented on internal/sdk/sdk_config.go
> +type APIObjectGroup struct {
Note: there is another comment that addresses this section of code: https://github.com/threeport/threeport/pull/258#issuecomment-2023818410

2024-03-28 15:12 UTC, lander2k2 approved these changes

2024-03-28 15:12 UTC, merged